#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-dynlm
Version  : 0.3.5
Release  : 8
URL      : https://cran.r-project.org/src/contrib/dynlm_0.3-5.tar.gz
Source0  : https://cran.r-project.org/src/contrib/dynlm_0.3-5.tar.gz
Summary  : Dynamic Linear Regression
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-car
Requires: R-lmtest
Requires: R-pbkrtest
Requires: R-zoo
BuildRequires : R-car
BuildRequires : R-lmtest
BuildRequires : R-pbkrtest
BuildRequires : R-zoo
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n dynlm

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489127604

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1489127604
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library dynlm
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library dynlm


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/dynlm/CITATION
/usr/lib64/R/library/dynlm/DESCRIPTION
/usr/lib64/R/library/dynlm/INDEX
/usr/lib64/R/library/dynlm/Meta/Rd.rds
/usr/lib64/R/library/dynlm/Meta/data.rds
/usr/lib64/R/library/dynlm/Meta/hsearch.rds
/usr/lib64/R/library/dynlm/Meta/links.rds
/usr/lib64/R/library/dynlm/Meta/nsInfo.rds
/usr/lib64/R/library/dynlm/Meta/package.rds
/usr/lib64/R/library/dynlm/NAMESPACE
/usr/lib64/R/library/dynlm/NEWS
/usr/lib64/R/library/dynlm/R/dynlm
/usr/lib64/R/library/dynlm/R/dynlm.rdb
/usr/lib64/R/library/dynlm/R/dynlm.rdx
/usr/lib64/R/library/dynlm/data/Rdata.rdb
/usr/lib64/R/library/dynlm/data/Rdata.rds
/usr/lib64/R/library/dynlm/data/Rdata.rdx
/usr/lib64/R/library/dynlm/help/AnIndex
/usr/lib64/R/library/dynlm/help/aliases.rds
/usr/lib64/R/library/dynlm/help/dynlm.rdb
/usr/lib64/R/library/dynlm/help/dynlm.rdx
/usr/lib64/R/library/dynlm/help/paths.rds
/usr/lib64/R/library/dynlm/html/00Index.html
/usr/lib64/R/library/dynlm/html/R.css
